# Generated by Django 4.2.13 on 2024-06-06 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                # Публичный - UUID
                ('idx', models.UUIDField(max_length=32)),

                # Тип груза
                ('cargo_type', models.CharField(default="object", null=False, max_length=255)),

                # Маршрут: От - До
                ('cargo_inf_to', models.CharField(null=False, max_length=255)),
                ('cargo_inf_from', models.CharField(null=False, max_length=255)),

                # Описание (Объем и размер)
                ('cargo_inf_size', models.CharField(null=False, max_length=255)),
                ('cargo_inf_wht', models.CharField(null=False, max_length=255)),

                # Время отправки
                ('cargo_deliv_start_at', models.DateTimeField(auto_now_add=False, null=False)),
                ('cargo_deliv_end_at', models.DateTimeField(auto_now_add=False, null=False)),

                # Статус
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('pending_accept', 'Pending Accepted'),
                             ('cancelled', 'Cancelled'), ('appeal', 'Appeal'),
                             ('appeal_consider', 'Appeal Consideration')],
                    default='pending_accept', max_length=255)),

                #
                ('description', models.TextField()),

                # Комментарий
                ('comment', models.TextField()),

                # Отправитель
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders',
                                             to=settings.AUTH_USER_MODEL)),
                # Перевозчик
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='courier_orders', to=settings.AUTH_USER_MODEL)),

                # Auto time
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
