# Generated by Django 4.2.13 on 2024-06-10 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# from backend.orders.models import Order

# from orders.models import Order  # Update the import statement


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),  # Assuming 0001_initial is the previous migration
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Публичный - UUID
                ('idx', models.UUIDField(max_length=32)),
                # Инфо о офере
                ('offer_amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
                # Заказ
                ('order', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, related_name='offers',
                                            to='orders.Order')),
                # Откликнувшийся
                ('courier',
                 models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='courier_offers',
                                   to=settings.AUTH_USER_MODEL)),

                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
