# Generated by Django 4.2.13 on 2024-06-17 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_offers_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idx', models.CharField(default=uuid.uuid4(), max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_chats',
                                             to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='courier_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_chats',
            },
        ),
        migrations.CreateModel(
            name='OrderChatMsg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                           to='orders.orderchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_chats_msgs',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='idx',
            field=models.CharField(default=uuid.uuid4(), max_length=255),
        ),
        migrations.AddField(
            model_name='orderchat',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats',
                                    to='orders.order'),
        ),
    ]
